language: node_js
env:
  - VUE_APP_VERSION = 'covid19-leaflet-docker v0.2'
node_js:
  - 14
cache:
  directories:
    - node_modules
  install:
    - npm i -g yarn
    - yarn install
  script:
    - yarn test 
